# Generated by Django 4.1.10 on 2024-05-21 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('ethereum_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('usdt_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, max_length=5000, null=True)),
                ('message2', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin', models.CharField(max_length=150)),
                ('ethereum', models.CharField(max_length=150)),
                ('tether_USDT', models.CharField(max_length=150)),
                ('ERC20_address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteVisitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(default='no data', max_length=100)),
                ('address', models.CharField(default='no data', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Under review', 'Under review'), ('Failed', 'Failed'), ('Approved', 'Approved')], default='Checking', max_length=30)),
                ('status_message', models.TextField(blank=True, max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('RequestID', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_login', models.BooleanField(default=True)),
                ('Nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('Profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('Deposits', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('Bonus', models.DecimalField(blank=True, decimal_places=2, default=15.0, max_digits=10, null=True)),
                ('Profits', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('AccountManager', models.CharField(blank=True, default='No assigned Trader', max_length=255, null=True)),
                ('Withdrawal_limit', models.DecimalField(blank=True, decimal_places=2, default=7000.0, max_digits=10, null=True)),
                ('card_pin', models.IntegerField(default=0)),
                ('TradeIsActive', models.BooleanField(default=False)),
                ('CanWithraw', models.BooleanField(default=False)),
                ('TradeStatus', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('No Trade', 'No Trade')], default='No Trade', max_length=30)),
                ('VerificationStatus', models.CharField(blank=True, choices=[('Verified', 'Verified'), ('Failed', 'Failed'), ('Under review', 'Under Review'), ('Awaiting', 'Awaiting')], default='Awaiting', max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ethereum_address', models.CharField(blank=True, max_length=255, null=True)),
                ('usdt_TRC20_address', models.CharField(blank=True, max_length=255, null=True)),
                ('usdt_ERC20_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome!!', max_length=100)),
                ('message', models.TextField(default='Thank you for joining us. Should you have any questions or concerns, kindly open a chat and an admin will be assigned to you.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='is_verified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('verification_code', models.IntegerField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IDME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='email_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(blank=True, max_length=255, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepositAmount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('Network', models.CharField(blank=True, max_length=100, null=True)),
                ('Proof', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('status', models.CharField(choices=[('No deposit', 'No Deposit'), ('Failed', 'Failed'), ('Under review', 'Under review'), ('Confirmed', 'Confirmed')], default='', max_length=50)),
                ('status_message', models.TextField(blank=True, max_length=5000, null=True)),
                ('requestID', models.CharField(blank=True, default='', max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField()),
                ('cvv', models.IntegerField(blank=True, null=True)),
                ('available_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('card_status', models.CharField(choices=[('Not activated', 'Not activated'), ('Activated', 'Activated'), ('Blocked', 'Blocked')], default='Not activated', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoBalances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_balance', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('ethereum_balance', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('usdt_balance', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deposits', models.CharField(blank=True, default='Deposits', editable=False, max_length=10, verbose_name='deposits')),
                ('deposits_day_one', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('deposits_day_two', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('deposits_day_three', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('deposits_day_four', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('deposits_day_five', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('profits', models.CharField(blank=True, default='Profits', editable=False, max_length=10, verbose_name='profits')),
                ('profits_day_one', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('profits_day_two', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('profits_day_three', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('profits_day_four', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('profits_day_five', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('losses', models.CharField(blank=True, default='Profits', editable=False, max_length=10, verbose_name='losses')),
                ('losses_day_one', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('losses_day_two', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('losses_day_three', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('losses_day_four', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('losses_day_five', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
