# Generated by Django 5.0 on 2024-05-27 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPurse_v2', '0002_minimumdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alert_user',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('micro', 'Micro'), ('standard', 'Standard'), ('premium', 'Premium'), ('elite', 'Elite'), ('premium-yields', 'Premium Yields'), ('Signatory', 'Signatory')], default='micro', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration', models.CharField(max_length=100)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
