# Generated by Django 5.0 on 2024-05-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPurse_v2', '0003_userprofile_alert_user_investments'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='waiver',
            field=models.BooleanField(default=False),
        ),
    ]
