# Generated by Django 5.0 on 2024-05-28 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPurse_v2', '0006_investments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrequest',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
