# Generated by Django 5.0 on 2024-05-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPurse_v2', '0007_cardrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
