# Generated by Django 5.0 on 2024-05-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPurse_v2', '0008_alter_cardrequest_date_alter_investments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrequest',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
